### ISSUE TITLE
Update events - missing documentation?

### ISSUE THREAD

**Issue by fyodorvi** [launchdarkly/node-server-sdk#94] opened 2018-06-05 05:58 UTC
I read all the documentation I could find on the SDK, but I've found no mentions on how you subscribe to an update event (or even if there is an updated event at all). I looked into the source and seems that `FeatureStoreEventWrapper` does indeed emit an `update` and `update:${key}` events. Is it something that shouldn't be used?

**Comment by eli-darkly** [comment] 2018-06-05 22:18
Sorry about that! That feature was added a few months ago due to a customer request, and we never got around to documenting it for everyone else - thanks for bringing that to our attention. We will update the docs ASAP.

As for whether it should be used: you can use it, but there is currently a limitation you should be aware of. If you get an `update:A` event, then it means flag A has been edited— specifically flag A itself. The problem is, that's not the only way the flag's value can change. If flag A uses flag B as a prerequisite, or refers to user segment S, then editing B or S could also cause A's value to change, yet you will not see an `update:A` event. This is not ideal, and we will probably change it soon so that your application logic will not need to worry about these internal details of how the flag is defined.

**Comment by eli-darkly** [comment] 2019-10-23 19:23
We did add documentation for this some time ago, but the limitation described in the previous comment has been fixed in the 5.9.2 release.

**Closed by eli-darkly** 2019-10-23 19:23 UTC
