### ISSUE TITLE
httpErrorMessage not properly stringified

### ISSUE THREAD

**Issue by Pipo93** [launchdarkly/node-server-sdk#263] opened 2022-11-09 09:53 UTC
**Describe the bug**
We received more than 100 warning logs today where it is impossible to detect the actual root cause for the error: `["2022-11-09T03:40:00.141Z"] Received I/O error ([object Object]) for streaming request - will retry`.

Looks like in https://github.com/launchdarkly/node-server-sdk/blob/main/messages.js#L10 the error object is not properly stringified. 

**To reproduce**
It is hard to reproduce on our side but it should be possible by calling httpErrorMessage with an error object not containing a message.

**Expected behavior**
The actual error is properly logged to the warning message.

**Logs**
`["2022-11-09T03:40:00.141Z"] Received I/O error ([object Object]) for streaming request - will retry`

**SDK version**
6.4.3

**Language version, developer tools**
node v16.14.2

**OS/platform**
Docker node16 image

**Comment by kinyoklion** [comment] 2022-11-10 17:50
Hello @Pipo93,

Thank you for raising this issue.

We will look into how we are getting an error without a status or a message. I would be hesitant to stringify it though.

_Filed internally as 176346_

Thanks,
Ryan

**Comment by kinyoklion** [comment] 2022-12-09 17:22
Hey @Pipo93,

It looks like this will only happen when the underlying request either completes, or closes prematurely, but there is no error. In this case the event source raises an 'end' event, which doesn't have a message, and the node server doesn't handle that correctly. I will provide another update once we have released a fix.

Thanks,
Ryan

**Comment by praxxis** [comment] 2023-07-24 20:29
We can reproduce this by connecting to an ld-relay implementation in streaming mode, when the relay has a [`maxClientConnectionTime`](https://github.com/launchdarkly/ld-relay/blob/56d1513b5e7153174fb97a5198b2450efd01f51d/docs/configuration.md?plain=1#L59) set. It kills the connection every ~5 minutes, causing `Received I/O error ([object Object]) for streaming request - will retry` to be logged as a warning.

**Comment by kinyoklion** [comment] 2024-04-29 20:02
This is fixed in `@launchdarkly/node-server-sdk` version 9.4.1.

- The js-eventsource has been updated to report a message in the case of an unexpected disconnect.
- The server has been updated to use the corresponding version.
- If there is no message a default message is now shown instead of logging the object.

**Closed by kinyoklion** 2024-04-29 20:02 UTC
